### PR TITLE
Mrshu/janitoring

### PR DESCRIPTION
**Pull request by mrshu**
janitoring: Fixed whitespace in PixyViSy.h
- The codebase should be consistent with regards to whitespace. That is
  what this commit enforeces.

### CODE REVIEW

**Comment by mrshu** [comment]
@vargac I fixed a few things you introduced in #6 and also included a basic README.

**Comment by vargac** [comment]
@mrshu I think it can be merged

**Comment by mrshu** [comment]
@vargac do not be afraid to push that big green button =)

**Comment by vargac** [comment]
@mrshu OK, I'm pushing :D

**Pull request merged**
